ros2_control_demo_robot_manager:
  ros__parameters:
    DemoRobot:
      name: "ROS2-C Demo Robot"
      has_hardware: True
      has_robots: False
      has_sensors: True
      has_tools: True
      RobotHardware:
        type: "ros2_control_demo_hardware/DemoRobotHardwareHeadless"
        has_communication_interface: True
        HardwareCommunicationInterface:
          type: "ros2_control_communicaiton_interface/DemoRobotCommunicationHeadless"

      joints: [jointX, jointY]
      actuators:
        jointX:
          name: "jointX_position_actuator"
          type: "ros2_control_components/VelocityActuator"
          can_read: True
          n_dof: 1
          min_values: [-1]
          max_values: [1]

        jointY:
          name: "jointY_velocity_actuator"
          type: "ros2_control_components/PositionActuator"
          n_dof: 1
          min_values: [-0.5]
          max_values: [1]

      sensors:
        jointX:
          name: "jointX_velocity_sensor"
          type: "ros2_control_components/VelocitySensor"
          n_dof: 1

        jointY:
          name: "jointY_velocity_sensor"
          type: "ros2_control_components/VelocitySensor"
          n_dof: 1

      #tools:
        #sensor_names: ["touch_sensor"]
        #sensors:
          #touch_sensor:
            #name: "tcp_touch_sensor"
            #type: "ros2_control_demo_components/TouchSensor"
            #frame_id: "tcp"
            #n_dof: 1
